### PR TITLE
Basic downloader 

### PR DESCRIPTION
**Pull request by rhnvrm**
sample:
`python generate_pdf.py`
`Name of tutorial? java`

### CODE REVIEW

**Comment by manrajgrover** [comment]
@rhnvrm Hey! Thank you for this. However I was planning to generate PDF on my own but then I couldn't find any good Python Library for converting HTML to PDF.

So lets go with this for now. If you have any good working library in your knowledge, please share.

I'll have a look at code positively by tomorrow.

**Comment by rhnvrm** [comment]
I've not worked on any such library but I found [pdfkit](http://stackoverflow.com/a/23761093/790971) which might be useful. It requires [wkhtmltopdf](https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf) to be installed. It seems to be working fine on my machine.

```
import pdfkit
pdfkit.from_url('http://google.com', 'out.pdf')
```

In the case of tutorialspoint.com, they already host their tutorials in pdf format on their server although when we goto the [pdf download page](http://www.tutorialspoint.com/java/java_pdf_version.htm) via their html tutorials link we see a paywall but under it there is a link for the [download](http://www.tutorialspoint.com/java/java_tutorial.pdf).

**Comment by manrajgrover** [comment]
I did use this library. But it was failing to fetch all pages if we provide it with a list of links.

**Comment by rhnvrm** [comment]
Yes, this seems to be the issue, right?
`This version of wkhtmltopdf is build against an unpatched version of QT, and does not support more then one input document.
`

I found another library just now called WeazyPrint. `pip install WeasyPrint` and usage details can be found [here](http://weasyprint.org/docs/tutorial/#as-a-python-library)

**Pull request merged**
